AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    lambda-s3-zip

    Sample SAM Template for lambda-s3-zip

Resources:

    lambdaS3Zip:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Timeout: 300
            MemorySize: 1024

Outputs:

    lambdaS3Zip:
      Description: "Lambda Function Name"
      Value: !Ref lambdaS3Zip

    lambdaS3ZipArn:
      Description: "Lambda Function ARN"
      Value: !GetAtt lambdaS3Zip.Arn

