AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: lambda-s3-zip
    Description: Lambda function that compressess a given S3 file and saves the output back to S3
    Author: Nestor Carvantes
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['lambda', 's3', 'zip', 'compress']
    HomePageUrl: https://github.com/carvantes/lambda-s3-zip
    SemanticVersion: 0.1.0
    SourceCodeUrl: https://github.com/carvantes/lambda-s3-zip

Resources:

    lambdaS3Zip:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: src/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Timeout: 300
            MemorySize: 1024

Outputs:

    lambdaS3Zip:
      Description: "Lambda Function Name"
      Value: !Ref lambdaS3Zip

    lambdaS3ZipArn:
      Description: "Lambda Function ARN"
      Value: !GetAtt lambdaS3Zip.Arn

